name: Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  pullRequestValidator:
    name: Pull Request Validator
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - name: Validate Pull Request
        uses: Ash258/Scoop-GithubActions@stable-win
        env:
          SHOVEL: "1"
          GITH_EMAIL: ${{ secrets.GITH_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
